# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Create Firebase File
        uses: 1arp/create-a-file-action@0.2
        with:
          path: 'src'
          file: 'FIREBASE_CONFIG.js'
          content: |
            export const firebaseConfig = {
              apiKey: "${{secrets.FIREBASE_API_KEY}}",
              authDomain: "${{secrets.FIREBASE_AUTH_DOMAIN}}",
              databaseURL: "${{secrets.FIREBASE_DATABASE_URL}}",
              projectId: "${{secrets.FIREBASE_PROJECT_ID}}",
              storageBucket: "${{secrets.FIREBASE_STORAGE_BUCKET}}",
              messagingSenderId: "${{secrets.FIREBASE_MESSAGING_SENDER_ID}}",
            };
      
      # Setup node environment
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          # Select node version
          node-version: '12.x' 

      # Run npm i to get dev dependencies
      - name: Run npm install
        run: npm install

      # Step to Build code 
      - name: Build Code
        run: npm run build

      # Step to deploy code
      - name: Deploy  
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          # For authentication via github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Change target branch 
          BRANCH: gh-pages 
          # Folder where the code is built
          FOLDER: build
          # Clean push
          CLEAN: true

      # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
